cc_binary(
  name = "main",
  srcs = [
    "main.cc"
  ],
  deps = [
    "//demo-01:main_lib"
  ]
)

cc_library(
  name = "main_lib",
  srcs = [
    "circle_strategy.cc",
    "triangle_strategy.cc",
    "rectangle_strategy.cc",
    "context.cc"
  ],
  deps = []
)
