cc_binary(
  name = "main",
  srcs = [
    "main.cc",
  ],
  deps = [
    ":publisher_subscriber"
  ]
)

cc_library(
  name = "publisher_subscriber",
  srcs = [
    "publisher.cc",
    "performance_publisher.cc",
    "mcall_subscriber.cc"
  ],
  deps = []
)
