cc_binary(
  name = "main",
  srcs = [
    "main.cc"
  ],
  deps = [
    ":maze"
  ]
)

cc_library(
  name = "maze",
  srcs = [
    "room.cc",
    "door.cc",
    "wall.cc",
    "maze_creator.cc",
    "bombed_door.cc",
    "bombed_maze_creator.cc"
  ],
  deps = []
)


