cc_binary(
  name = "main",
  srcs = [
    "main.cc"
  ],
  deps = [
    ":product"
  ]
)

cc_library(
  name = "product",
  srcs = [
    "concreate_product.cc",
    "concreate_creator.cc"
  ],
  deps= []
)
