cc_binary(
  name = "main",
  srcs = [
    "main.cc"
  ],
  deps = [
    ":computing"
  ]
)

cc_library(
  name = "computing",
  srcs = [
    "add_computing.cc",
    "minus_computing.cc"
  ],
  deps = []
)
